-- MySQL Script generated by MySQL Workbench
-- Mon May 25 12:54:43 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`planEntrenamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planEntrenamiento` (
  `id_Plan_Entrenamiento` INT NOT NULL AUTO_INCREMENT,
  `horario` DATETIME NOT NULL,
  `duracion` INT NOT NULL,
  `dieta` TEXT NOT NULL,
  `rutina` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `created_by` INT NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id_Plan_Entrenamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membresias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membresias` (
  `id_membresia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `beneficios` VARCHAR(200) NOT NULL,
  `precio` INT NOT NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `created_by` INT NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id_membresia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `edad` INT NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `created_by` INT NULL,
  `deleted` TINYINT(1) NULL,
  `id_Plan_Entrenamiento` INT NOT NULL,
  `membresias_id_membresia` INT NOT NULL,
  PRIMARY KEY (`id_Cliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  INDEX `fk_Clientes_planEntrenamiento_idx` (`id_Plan_Entrenamiento` ASC) VISIBLE,
  INDEX `fk_Clientes_membresias1_idx` (`membresias_id_membresia` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_planEntrenamiento`
    FOREIGN KEY (`id_Plan_Entrenamiento`)
    REFERENCES `mydb`.`planEntrenamiento` (`id_Plan_Entrenamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_membresias1`
    FOREIGN KEY (`membresias_id_membresia`)
    REFERENCES `mydb`.`membresias` (`id_membresia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrenador` (
  `id_Entrenadore` INT NOT NULL AUTO_INCREMENT,
  `salario` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `edad` INT NOT NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `created_by` INT NULL,
  `deleted` TINYINT(1) NULL,
  `Clientes_id_Cliente` INT NOT NULL,
  PRIMARY KEY (`id_Entrenadore`),
  INDEX `fk_Entrenador_Clientes1_idx` (`Clientes_id_Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Entrenador_Clientes1`
    FOREIGN KEY (`Clientes_id_Cliente`)
    REFERENCES `mydb`.`Clientes` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
